name: Unanimously Approved

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  unanimously-approved:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
